### ISSUE TITLE
Help with customizable_sale_receipt.tpl

### ISSUE THREAD

**Issue by aseitham** [merchantos/PrintTemplates#24]
Is there a way to push a second sales receipt out with this template.  We are using this template and it works great but we are wondering if we can get a second receipt to auto print.  We can just make it print two when we print but it print 2 credit card signature receipt which we don't need.  We would just like to have it print the sales receipt twice.  Let me know if this is possible.  
Thanks

**Comment by lukebowerman** [comment]
Hi - my apologies on not getting back to you on this sooner. Did you figure out a way to pull this off? I imagine duplicating the {{ _self.store_receipt(Sale,parameters) }} call would allow you to output two copies instead of a single.

**Comment by aseitham** [comment]
Yes I closed the issue because I did figure it out.  Had to modify it a little because I needed a page break for the autocutter on the printer.  Everything is working smooth.  The template has helped us a lot and thanks for getting back to me.

Sent from Windows Mail
